FORMAT: 1A
HOST: http://api.datasnap.io/v1.0

# Datasnap.io
Analytics API is the set of REST web services to send data to Datasnap for analysis.

Please @see http://help.datasnap.com/analytics_api.html for detailed use cases and design guide for the
best way to send us data.

# Events (AKA Indegestor)
Events related resources of the **Events API**

## Events Collection [/organization/${organization}/${app_name}/events/?api_key=${api_key}&data=${data}&redirect=${redirect}]


**Possible events that you can send your own:**

- user_opt_in_location
- user_opt_in_push_notifications
- user_opt_in_vendor
- beacon_arrived
- beacon_sighting
- beacon_departed
- interaction_tap
- interaction_view
- interaction_swipe
- interaction_shake

You CAN also append any other json properties as you want at any level that you would like.

The ones outlined below are provided and will be treated specially by Datasnap and can be automatically applied to your Reports Dimensions and Metrics. Otherwise we will need to work together to setup and map your custom fields to these fields.

**Timestamp Data Types**

Two time-related properties are included in your event automatically.
The properties “datasnap.timestamp” and “datasnap.created_at” are set at the time your event is recorded. You have the ability to overwrite the datasnap.timestamp property. This could be useful, for example, if you are backfilling historical data.
Be sure to use ISO-8601 Format. http://en.wikipedia.org/wiki/ISO_8601


**Url Parameter "data" encoding:**

The following encoding should be used when sending json information into the data URL Parameter

'URL Safe' base64 encoding, or "RFC4648 base64url (Base
64 Encoding with URL and Filename Safe Alphabet)

There are ready libraries that do this in Ruby, PHP, and Javascript.


Java Example:

java.util.Base64.getUrlEncoder().encodeToString("my fancyurl".getBytes());


Java w/ Apache Commons:

org.apache.commons.codec.binary.Base64.encodeBase64URLSafeString("mystring".getBytes())



**Special internal Datasnap fields:**

We denote these under the "datasnap" property in the root json payload. These will be automatically set for you
via one of our SDKs or via our backend server such as _timestamp_.
You can of course override these at any time but please be careful in doing so.


+ Parameters
    + api_key (required, string, `E9NZuB6A91e2J03PKA2g7wx0629czel8`) ... String `api-key` for the Datasnap account/organization (optional if you use Authorization header)
    + organization (required, number, ) ... Number `organization`
    + app_name (required, number, ) ... Number `app_name`
    + data (optional,string, `%20WERF%20` ) ... String `data`   ... RFC4648 base64url (Base64 Encoding with URL and Filename Safe Alphabet)
    + redirect (optional, string, `http://www.apple.com` ) ... String `redirect` ... URL that the user will be sent to when using the GET Tracking method.

### Create an Event [POST]


+ Request (application/json)

    + Headers

            Authorization: E9NZuB6A91e2J03PKA2g7wx0629czel8

    + Body

            {
                "event_type": "beacon_sighting",
                "place": {
                    "id": "placeid",
                    "address": "1805 san bernadino ave, SF, CA",
                    "geoFenceCircle": [
                        {
                            "radius": 100,
                            "visibility": "ORGANIZATION",
                            "location": {
                                "latitude": 32.89494374592149,
                                "longitude": -117.19603832579497
                            }
                        }
                    ],
                    "geofenceBeacon": [
                        {
                            "beacons": [
                                "beaconid1"
                            ],
                            "beacon_tags": [
                                "beacontag1",
                                "beacontag2"
                            ]
                        }
                    ],
                    "geoFencePolygon": [
                        {
                            "visibility": "ORGANIZATION",
                            "locations": [
                                {
                                    "latitude": 32.8953153522896,
                                    "longitude": -117.19559844351653
                                },
                                {
                                    "latitude": 32.8954009341414,
                                    "longitude": -117.19516929007415
                                },
                                {
                                    "latitude": 32.89564867061472,
                                    "longitude": -117.1949815354431
                                },
                                {
                                    "latitude": 32.89545949009762,
                                    "longitude": -117.19463284827117
                                },
                                {
                                    "latitude": 32.894986537037255,
                                    "longitude": -117.19496544218902
                                },
                                {
                                    "latitude": 32.894864920127866,
                                    "longitude": -117.19554479933623
                                }
                            ]
                        }
                    ]
                },
                "beacon": {
                    "id": "22222-eevs",
                    "ble_uuid": "ble_uuid",
                    "ble_vendor_uuid": "ble_vendor_uuid",
                    "ble_vendor_id": "ble_vendor_id",
                    "name": "Front Entrance",
                    "latitude": 11.22222,
                    "organization_ids": [
                        "orgid1",
                        "orgid2"
                    ],
                    "longitude": 123.444,
                    "visibility": "Private",
                    "battery_level": "BatteryLeveloftheBeacon",
                    "hardware": "HardwaretypeoftheBeacon",
                    "categories": [
                        {
                            "Sports": {
            
                            }
                        },
                        {
                            "Womens": {
                                "subcategories": [
                                    "golfshirts",
                                    "dresses"
                                ]
                            }
                        },
                        {
                            "Mens": {
            
                            }
                        }
                    ],
                    "tags": [
                        "womens",
                        "golf",
                        "shoes"
                    ]
                },
                "communication": {
                    "description": "mydescription",
                    "id": "commid",
                    "type": {
                        "id": "typeid",
                        "name": "PushNotificaion"
                    }
                },
                "user": {
                    "id": {
                        "mobile_device_ios_idfa": "092384",
                        "mobile_device_ios_openidfa": "09238dd4",
                        "mobile_device_ios_idfv": "092344",
                        "mobile_device_ios_udid": "123",
                        "datasnap_uuid": "datasnap_uuid",
                        "web_domain_userid": "",
                        "web_cookie": "foo",
                        "web_network_userid": "billybob",
                        "web_user_fingerprint": "web_user_fingerprint",
                        "web_analytics_company_z_cookie": "",
                        "global_distinct_id": "userid1234",
                        "global_user_ipaddress": "user_ipaddress",
                        "mobile_device_fingerprint": "2da076c7ad28740c0b2a9b7fa6077c4f",
                        "facebook_uid": "2234433",
                        "mobile_device_google_advertising_id": "googid",
                        "mobile_device_google_google_advertising_id_opt_in": "true",
                        "unknown": "unknownid",
                        "": ""
                    },
                    "audience": {
                        "Education": [
                            "College"
                        ],
                        "Age": [
                            "18-24"
                        ],
                        "Ethnicity": [
                            "Caucasian"
                        ],
                        "Kids": [
                            "NoKids"
                        ],
                        "Gender": [
                            "Male"
                        ],
                        "Interests": [
                            "Gettingfromheretothere",
                            "Biking",
                            "Automotive",
                            "Automotive.Cars"
                        ],
                        "Income": [
                            "$30-60k"
                        ]
                    },
                    "user_properties": {
                        "user_type": "VIP",
                        "user_spend": "high",
                        "engagement_time": "Greaterthan30minutes"
                    }
                },
                "campaign": {
                    "id": "campaignid",
                    "name": "camapign10%offshoes",
                    "subcampaigns": [
                        {
                            "id": "campaignid",
                            "name": "camapign11%offshoesmles"
                        }
                    ],
                    "targeting_rules": {
                        "id": "targetingid",
                        "rules": [
                            {
                                "id": "ruleid1",
                                "name": "retailandclothingruleforbackofstore",
                                "place_ids": [
                                    "placeid1"
                                ],
                                "audience": {
                                    "Education": [
                                        "NoCollege",
                                        "College",
                                        "GradSchool"
                                    ],
                                    "Age": [
                                        "18-24",
                                        "25-34",
                                        "35-44",
                                        "45-55",
                                        "55+"
                                    ],
                                    "Ethnicity": [
                                        "Caucasian",
                                        "AfricanAmerican",
                                        "Asian",
                                        "Hispanic",
                                        "Other"
                                    ],
                                    "Kids": [
                                        "NoKids",
                                        "HasKids"
                                    ],
                                    "Gender": [
                                        "Male",
                                        "Female"
                                    ],
                                    "Interests": [
                                        "Gettingfromheretothere",
                                        "Biking",
                                        "Automotive",
                                        "Automotive.Cars"
                                    ],
                                    "Income": [
                                        "$0-30k",
                                        "$30-60k",
                                        "$60-100k",
                                        "100k+"
                                    ]
                                },
                                "targeting_attributes": {
                                    "store_type": "retail",
                                    "product_type": "clothing"
                                }
                            },
                            {
                                "id": "ruleid2",
                                "name": "mycoolrule2",
                                "audience": {
                                    "Education": [
                                        "NoCollege",
                                        "College",
                                        "GradSchool"
                                    ],
                                    "Age": [
                                        "18-24",
                                        "25-34",
                                        "35-44",
                                        "45-55",
                                        "55+"
                                    ],
                                    "Ethnicity": [
                                        "Caucasian",
                                        "AfricanAmerican",
                                        "Asian",
                                        "Hispanic",
                                        "Other"
                                    ],
                                    "Kids": [
                                        "NoKids",
                                        "HasKids"
                                    ],
                                    "Gender": [
                                        "Male",
                                        "Female"
                                    ],
                                    "Interests": [
                                        "Gettingfromheretothere",
                                        "Biking",
                                        "Automotive",
                                        "Automotive.Cars"
                                    ],
                                    "Income": [
                                        "$0-30k",
                                        "$30-60k",
                                        "$60-100k",
                                        "100k+"
                                    ]
                                }
                            }
                        ]
                    },
                    "time_filter": {
                        "monday": {
                            "start": "08: 00",
                            "end": "13: 00"
                        },
                        "tuesday": {
                            "start": "08: 00",
                            "end": "22: 00"
                        }
                    },
                    "time_trigger": {
                        "monday": "08: 00",
                        "tuesday": "13: 00"
                    },
                    "communication": {
                        "id": "commid",
                        "communication_vendor_id": "airpush",
                        "name": "10% offPushnotification",
                        "type": "Push",
                        "content": {
                            "text": "get10%off!",
                            "description": "get10%offifyougotothe",
                            "image": "http: //appl.com/image.gif",
                            "html": "<p>Hithere!!get10%offnow!!</p>",
                            "url": "http: //www.apple.com"
                        }
                    }
                },
                "datasnap": {
                    "timestamp": "2012-12-14T20: 24: 01.123000+00: 00",
                    "location": {
                        "coordinates": [
                            -88.21337,
                            40.11041
                        ]
                    }
                }
            }


    + Schema

            {
                "type": "object",
                "required": false,
                "properties": {
                    "event_type": {
                        "type": ["string", "null"],
                        "required": true
                    },
                    "id": {
                        "type": "number",
                        "required": false
                    }
                }
            }



+ Response 200 (application/json)

        { "created": true}



### Create a Event via Image Pixel [GET]

This is used to perform pixel based tracking where its easier to embed into email and html <img /> tags and
harder to perform a more programmatic POST request.


+ Request (application/json)

    + Headers

            Authorization: E9NZuB6A91e2J03PKA2g7wx0629czel8

+ Response 200 (image/gif)

    + Headers

            Content-length:0
            Date:Tue, 15 Jul 2014 06:41:10 GMT
