FORMAT: 1A
HOST: https://api-events.datasnap.io/v1.0/



# Datasnap.io Analytics Events API
Use our set of REST API services to send analytics data to us.

Please @see http://help.datasnap.com/analytics_api.html for detailed use cases and design guide for the
best way to send us data.  

Terms and Conditions: http://staging.datasnap.io/terms.html#apiterms 

# Events 
Events related resources of the **Events API**

## Events Collection [/events/?api_key=${api_key}&data=${data}&redirect=${redirect}]


#STANDARD EVENTS
Standard events are treated specially by Datasnap and can be automatically applied to your Reports Dimensions and Metrics. You can also send non-standard events. You can work with datasnap.io to get these integrated into your reports.

###Diagnostic events
- **status_ping** - Event used to send a test message that can be used for health monitoring and testing.  Will not be rolled up into system.

###In App Opt In Events
- **opt_in_location**  The user has opted in to track their location and accepted all appropriate terms of use.
- **opt_in_push_notifications** The user has opted in to receieve push notifications.
- **opt_in_vendor** A user has opted in to the vendors specific terms.

###In App Interactions
- **app_installed** The user installed the app. Most mobile analytics platforms record this already but it is a useful enough event to provide it here.
- **interaction_tap**  Some tap has happened in the app. Can be associated with a camapign, communication, or just an app by itself. 
- **interaction_view** Some view has happened in the app. Can be associated with a camapign, communication, or just an app by itself.
- **interaction_swipe** Some swipe has happened in the app. Can be associated with a camapign, communication, or just an app by itself.
- **interaction_shake** Some shake has happened in the app. Can be associated with a camapign, communication, or just an app by itself.
- **interaction_tilt** Some tilt has happened in the app. Can be associated with a camapign, communication, or just an app by itself.

###Communication Events
- **communication_delivered** A communication has been delivered ot the user. It can be associated wiht a campaign or not.  For mobile these are typically push notifications or in App Modals.
- **campaign_request** The app has requested a campaign to be show to the user.
- **campaign_redemption** The user has redeemed a coupon or similar as part of the campaign.

###Beacon Events
- **beacon_arrived** A users first time receiving a broadcast from a particular beacon.
- **beacon_sighting** A user is within a particular beacon range and has received a broadcast from the beacon.
- **beacon_depart_vendor** This event can be thrown when a vendors's SDK detect an event. For some vendors this setting can be erroneous so its recommended ot track sperately for audit reporting. 
- **beacon_depart** A true departed event meaning the user has departed and we feel confident that this event is correct. Some folks use their own calulation to throw this event.
- **beacon_visit** A true user visit into a proximity or geotrigger.  This is many times calulated by looking at sighting data or inferred through the use of the departed event.
- **beacon_visit_vendor** A user visit into a proximity or geotrigger as sent by the beacon vendor.  This is used ot compare wiht the true calculation of the beacon_visit event.

###Geofence Events
- **geofence_arrive** A user has entered a Geofence.
- **geofence_sighting** A user is still in the Geofence after a interval based check of their location.
- **geofence_depart**  A user has left the Geofence. 


###Update Events
- Any top level properties such as place/campaign/beacon will be updated in our system if you pass along the dimension/meta fields such as beacon name. 
- You do not need to send these fields every time you send an event.
- You can also fire specific events such as place_update to clearly indicate that your updating the place/camapign/beacon data.


    - **place_update** indicated that a place update has occurred.. usually would only contain the place.
    - **campaign_update** indicated that a campaign update has occurred.. usually would only contain the campaign.
    - **beacon_update** indicated that a beacon update has occurred.. usually would only contain the beacon.


# NON-STANDARD EVENTS
- You CAN also append any other json properties as you want at any level that you would like.



# FORMATTING & DATATYPES

###User Identifiers
All use identifiers should be passed to the API as SHA1 hashed properties. We will be monitoring this and will let you know if you are nto doing this.

###Timestamp Data Types
- Two time-related properties are included in your event automatically.
- The properties “datasnap.timestamp” and “datasnap.created_at” are set at the time your event is recorded. You have the ability to overwrite the datasnap.timestamp property. This could be useful, for example, if you are backfilling historical data.
- Be sure to use ISO-8601 Format. http://en.wikipedia.org/wiki/ISO_8601

###Special internal Datasnap fields

- We denote these under the "datasnap" property in the root json payload. These will be automatically set for you
via one of our SDKs or via our backend server such as _timestamp_.
You can of course override these at any time but please be careful in doing so.

###URL Parameter "data" encoding
The following encoding should be used when sending json information into the data URL Parameter (There are ready libraries that do this in Ruby, PHP, and Javascript.)

- 'URL Safe' base64 encoding, or "RFC4648 base64url (Base 64 Encoding with URL and Filename Safe Alphabet)

### Authentication and API Keys

You will get a API Key and API Secret for access and add it to the headers as "Authorization:  Basic <PUT Base64 String Here>"

In order to authorize then base64 encode the key and secret together. For example
you can use this Linux command to do create this base64 string:


                echo -n "APIKey:APISecret" | openssl base64



###EXAMPLES

**Java Example:** java.util.Base64.getUrlEncoder().encodeToString("my fancyurl".getBytes());

**Java w/ Apache Commons:** org.apache.commons.codec.binary.Base64.encodeBase64URLSafeString("mystring".getBytes())


+ Parameters
    + api_key (optional, string, `E9NZuB6A91e2J03PKA2g7wx0629czel8`) ... String `api-key` for the Datasnap account/organization which is base64 encoded api key and api secret provided that has the Events API Permission (optional if you use Authorization header which is prefferred)
    + data (optional,string, `%20WERF%20` ) ... String `data`   ... RFC4648 base64url (Base64 Encoding with URL and Filename Safe Alphabet)
    + redirect (optional, string, `http://www.apple.com` ) ... String `redirect` ... URL that the user will be sent to when using the GET Tracking method.

### Create an Event [POST]


+ Request (application/json)

    + Headers

            Authorization: Basic E9NZuB6A91e2J03PKA2g7wx0629czel8

    + Body

            [
            {
                "event_type": "beacon_depart",
                "organization_ids": [
                    "3HRhnUtmtXnT1UHQHClAcP"
                ],
                "project_ids": [
                    "3HRhnUtmtXnT1UHQHClAcP"
                ],
                "place": {
                    "id": "placeid",
                    "name": "Mission District",
                    "tags": [
                        "womens",
                        "golf",
                        "shoes"
                    ],
                    "address": {
                        "address1": "103 west street",
                        "address2": "",
                        "city": "San Francisco",
                        "region": "CA",
                        "zip": 94107,
                        "zip4": 3422
                    },
                    "last_place": "placeid-3",
                    "geofences": [
                        {
                            "geofenceid": "geofenceid2"
                        },
                        {
                            "geofenceid": "geofenceid2"
                        }
                    ],
        
                    "beacons": [
                        {
                            "beaconid": "beaconid1"
                        },
                        {
                            "beaconid": "beaconid2"
                        }
                    ]
                },
                "geo_fence": {
                    "id": "geofence2",
                    "name": "SF Gelen Park",
                    "visibility": "ORGANIZATION",
        
                    "tags": [
                        "womens",
                        "golf",
                        "shoes"
                    ],
                    "geofence_circle": {
                        "radius": 100,
                        "location": {
                            "latitude": 32.89494374592149,
                            "longitude": -117.19603832579497
                        }
                    },
                    "geofence_polygon": {
                        "locations": [
                            {
                                "latitude": 32.8953153522896,
                                "longitude": -117.19559844351653
                            },
                            {
                                "latitude": 32.8954009341414,
                                "longitude": -117.19516929007415
                            },
                            {
                                "latitude": 32.89564867061472,
                                "longitude": -117.1949815354431
                            },
                            {
                                "latitude": 32.89545949009762,
                                "longitude": -117.19463284827117
                            },
                            {
                                "latitude": 32.894986537037255,
                                "longitude": -117.19496544218902
                            },
                            {
                                "latitude": 32.894864920127866,
                                "longitude": -117.19554479933623
                            }
                        ]
                    }
        
                },
                "gps_position":{
                    "location": {
                        "coordinates": [
                            -88.21337,
                            40.11041
                        ]
                    },
                    "altitude": 13.00,
                    "accuracy": 10,
                    "course": 77.34375,
                    "speed": 4.0
                },
                "beacon": {
                    "identifier": "SHDG-28AHD",
                    "ble_uuid": "ble_uuid",
                    "ble_vendor_uuid": "ble_vendor_uuid",
                    "ble_vendor_id": "ble_vendor_id",
                    "rssi": 80,
                    "previous_rssi": 70,
                    "name": "Front Entrance",
                    "dwell_time": 600000,
                    "is_mobile": false,
                    "start_time": "2014-12-14T20:24:01.123000+00:00",
                    "last_update_time": "2014-12-14T20:24:01.123000+00:00",
                    "latitude": 11.22222,
                    "longitude": 123.444,
                    "visibility": "Private",
                    "battery_level": "50",
                    "temperature": "68.32",
                    "hardware": "HardwaretypeoftheBeacon",
                    "categories": [
                        {
                            "Sports": {}
                        },
                        {
                            "Womens": {
                                "subcategories": [
                                    "golfshirts",
                                    "dresses"
                                ]
                            }
                        },
                        {
                            "Mens": {}
                        }
                    ],
                    "tags": [
                        "womens",
                        "golf",
                        "shoes"
                    ]
                },
                "communication": {
                    "description": "mydescription",
                    "tags": [
                        "womens",
                        "golf",
                        "shoes"
                    ],
                    "id": "commid",
                    "status": "active",
                    "communication_vendor_id": "airpush",
                    "name": "10% offPushnotification",
                    "type": {
                        "id": "typeid",
                        "name": "PushNotificaion"
                    },
                    "content": {
                        "text": "get10%off!",
                        "description": "get10%offifyougotothe",
                        "image": "http: //appl.com/image.gif",
                        "html": "<p>Hithere!!get10%offnow!!</p>",
                        "url": "http: //www.apple.com"
                    }
                },
                "user": {
                    "tags": [
                        "womens",
                        "golf",
                        "shoes"
                    ],
                    "id": {
                        "mobile_device_bluetooth_identifier": "8c4e1f232810d11be96edf47674f5641296a76f5",
                        "mobile_device_ios_idfa": "1a847de9f24b18eee3fac634b833b7887b32dea3",
                        "mobile_device_ios_openidfa": "09238dd4",
                        "mobile_device_ios_idfv": "092344",
                        "mobile_device_ios_udid": "123",
                        "datasnap_uuid": "datasnap_uuid",
                        "web_domain_userid": "",
                        "web_cookie": "foo",
                        "domain_sessionid": "fqr9fgwer8vb9",
                        "web_network_userid": "billybob",
                        "web_user_fingerprint": "web_user_fingerprint",
                        "web_analytics_company_z_cookie": "",
                        "global_distinct_id": "userid1234",
                        "global_user_ipaddress": "user_ipaddress",
                        "mobile_device_fingerprint": "2da076c7ad28740c0b2a9b7fa6077c4f",
                        "facebook_uid": "2234433",
                        "mobile_device_google_advertising_id": "googid",
                        "mobile_device_google_google_advertising_id_opt_in": "true",
                        "unknown": "unknownid",
                        "": ""
                    },
                    "opt_in_location": true,
                    "opt_in_push_notifications": true,
                    "opt_in_vendor": true,
                    "audience": {
                        "Education": [
                            "College"
                        ],
                        "Age": [
                            "18-24"
                        ],
                        "Ethnicity": [
                            "Caucasian"
                        ],
                        "Kids": [
                            "NoKids"
                        ],
                        "Gender": [
                            "Male"
                        ],
                        "Interests": [
                            "Gettingfromheretothere",
                            "Biking",
                            "Automotive",
                            "Automotive.Cars"
                        ],
                        "Income": [
                            "$30-60k"
                        ]
                    },
                    "user_properties": {
                        "user_type": "VIP",
                        "user_spend": "high",
                        "engagement_time": "Greaterthan30minutes"
                    }
                },
                "campaign": {
                    "id": "campaignid",
                    "name": "camapign10%offshoes",
                    "tags": [
                        "womens",
                        "golf",
                        "shoes"
                    ],
                    "subcampaigns": [
                        {
                            "id": "campaignid",
                            "name": "camapign11%offshoesmles"
                        }
                    ],
                    "targeting_rules": {
                        "id": "targetingid",
                        "rules": [
                            {
                                "id": "ruleid1",
                                "name": "retailandclothingruleforbackofstore",
                                "place_ids": [
                                    "placeid1"
                                ],
                                "audience": {
                                    "Education": [
                                        "NoCollege",
                                        "College",
                                        "GradSchool"
                                    ],
                                    "Age": [
                                        "18-24",
                                        "25-34",
                                        "35-44",
                                        "45-55",
                                        "55+"
                                    ],
                                    "Ethnicity": [
                                        "Caucasian",
                                        "AfricanAmerican",
                                        "Asian",
                                        "Hispanic",
                                        "Other"
                                    ],
                                    "Kids": [
                                        "NoKids",
                                        "HasKids"
                                    ],
                                    "Gender": [
                                        "Male",
                                        "Female"
                                    ],
                                    "Interests": [
                                        "Gettingfromheretothere",
                                        "Biking",
                                        "Automotive",
                                        "Automotive.Cars"
                                    ],
                                    "Income": [
                                        "$0-30k",
                                        "$30-60k",
                                        "$60-100k",
                                        "100k+"
                                    ]
                                },
                                "targeting_attributes": {
                                    "store_type": "retail",
                                    "product_type": "clothing"
                                }
                            },
                            {
                                "id": "ruleid2",
                                "name": "mycoolrule2",
                                "audience": {
                                    "Education": [
                                        "NoCollege",
                                        "College",
                                        "GradSchool"
                                    ],
                                    "Age": [
                                        "18-24",
                                        "25-34",
                                        "35-44",
                                        "45-55",
                                        "55+"
                                    ],
                                    "Ethnicity": [
                                        "Caucasian",
                                        "AfricanAmerican",
                                        "Asian",
                                        "Hispanic",
                                        "Other"
                                    ],
                                    "Kids": [
                                        "NoKids",
                                        "HasKids"
                                    ],
                                    "Gender": [
                                        "Male",
                                        "Female"
                                    ],
                                    "Interests": [
                                        "Gettingfromheretothere",
                                        "Biking",
                                        "Automotive",
                                        "Automotive.Cars"
                                    ],
                                    "Income": [
                                        "$0-30k",
                                        "$30-60k",
                                        "$60-100k",
                                        "100k+"
                                    ]
                                }
                            }
                        ]
                    },
                    "time_filter": {
                        "monday": {
                            "start": "08: 00",
                            "end": "13: 00"
                        },
                        "tuesday": {
                            "start": "08: 00",
                            "end": "22: 00"
                        }
                    },
                    "time_trigger": {
                        "monday": "08: 00",
                        "tuesday": "13: 00"
                    },
                    "communication_ids": [
                        "commid1", "commid2"
                    ]
                },
                "datasnap": {
                "timestamp": "2014-12-14T20:24:01.123000+00:00",
                "timezone": "US/Eastern",
                "created": "2014-12-12T20:24:01.123000+00:00",
                    "location": {
                        "coordinates": [
                            -88.21337,
                            40.11041
                        ]
                    },
                    "txn_id": "fgfgbrrwvb",
                    "device": {
                        "user_agent": "Mozilla/5.0 (Linux; U; Android 4.0.3; ko-kr; LG-L160L Build/IML74K) AppleWebkit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30",
                        "ip_address": "127.1.1.1",
                        "platform": "ios",
                        "os_version": "7.0",
                        "model": "iPhone5",
                        "manufacturer": "Apple",
                        "name": "hashed device name",
                        "vendor_id": "63A7355F-5AF2-4E20-BE55-C3E80D0305B1",
                        "carrier_name": "Verizon",
                        "country_code": "1",
                        "network_code": "327"
                    }
                }
            },
            {
                "event_type": "beacon_sighting"
            }
            ]

+ Response 200 (application/json)

        { "created": true}



### Create a Event via Image Pixel [GET]

This is used to perform pixel based tracking where its easier to embed into email and html <img /> tags and
harder to perform a more programmatic POST request.


+ Request (application/json)

    + Headers

            Authorization: Basic E9NZuB6A91e2J03PKA2g7wx0629czel8

+ Response 200 (image/gif)

    + Headers

            Content-length:0
            Date:Tue, 15 Jul 2014 06:41:10 GMT
